spring:
    profiles:
        active: dev
    datasource:
        url: http://default
        username: default
        password: defaultPwd
        driverClassName: com.mysql.jdbc.Driver
server:
    port: 8088
    servlet:
        context-path: /api

    


